// One affirmation per level 1–1000
// Grouped by tier feel — Newbie (1–249), Experienced (250–499), Enlightened (500–1000)

const AFFIRMATIONS: string[] = [
  // Levels 1–50 — First steps, gentle encouragement
  "Every breath you take is a step toward peace.",
  "You showed up. That is everything.",
  "Stillness lives inside you — you just found the door.",
  "The journey of a thousand levels begins with one breath.",
  "You are already exactly where you need to be.",
  "Quiet minds hear the loudest truths.",
  "Today you chose yourself. Well done.",
  "Even a single minute of peace changes the whole day.",
  "You are building something no one can take from you.",
  "The world needs your calm — and you are creating it.",
  "Progress is not loud. It is quiet, like your breath.",
  "You are more present today than yesterday.",
  "This practice is your gift to yourself.",
  "Peace is not found — it is remembered.",
  "Your mind grows stronger every time you sit.",
  "You are not running from the world. You are learning to stand in it.",
  "Softness is strength. You are practicing both.",
  "Each session plants a seed you will one day sit in the shade of.",
  "You did not quit. That is the whole secret.",
  "You are allowed to be still in a busy world.",
  "Meditation is the bravest thing most people never try.",
  "You are becoming someone who knows how to breathe.",
  "The monkey mind is quieting. You are doing that.",
  "Rest is not laziness — it is wisdom.",
  "One breath at a time, you are changing your life.",
  "Your nervous system thanks you for this.",
  "You are learning the language of your own mind.",
  "Silence is not empty. You are finding that out.",
  "You are planting calm in a field of chaos.",
  "The most powerful place you can be is right here.",
  "You returned. That is the practice.",
  "Inner peace is not a destination — it is a daily practice, like today.",
  "You are not behind. You are exactly on time.",
  "Your future self will thank you for sitting today.",
  "Every exhale releases what no longer serves you.",
  "You are learning to listen before you react.",
  "Stillness is your superpower.",
  "You chose peace over noise. That takes courage.",
  "You are growing in ways that do not show yet.",
  "The world is louder than ever. Your calm is a revolution.",
  "You are learning that nothing is an emergency in this moment.",
  "Breath by breath, you are healing.",
  "You showed up for yourself today. That matters deeply.",
  "Something in you is settling. Trust it.",
  "You are not your thoughts. You are the one watching them.",
  "Peace is something you practice, and you are practicing.",
  "You are worth every second of this quiet.",
  "A calmer you makes the whole world a little calmer.",
  "You are building the foundation of an unshakeable mind.",
  "Every level is a promise you kept to yourself.",

  // Levels 51–100 — Building momentum
  "The habit is forming. Your mind is learning.",
  "You are no longer a beginner at being present.",
  "Each session is a deposit into your peace account.",
  "You are learning that you can always come back to the breath.",
  "Your consistency is your commitment to yourself.",
  "Fifty sessions in, and your mind is changing. You can feel it.",
  "The gap between thought and reaction is widening. That is you.",
  "You are becoming someone who chooses calm.",
  "Your breath has always been here. You are just listening now.",
  "You have sat with yourself enough times to trust yourself.",
  "Returning again and again is the whole practice.",
  "Your dedication is already reshaping your brain.",
  "You are building a refuge no one else can enter or destroy.",
  "Stress has less grip on you than it used to.",
  "You are learning the art of letting go.",
  "The mind you are training now will serve you for life.",
  "You have found something most people search for forever.",
  "Your practice is real. Your progress is real.",
  "You are becoming harder to rattle.",
  "The noise gets quieter the more you do this.",
  "You are a meditator now. Fully, completely.",
  "Your presence is your greatest power.",
  "You have come further than you realize.",
  "Every time you sit, you strengthen the muscle of peace.",
  "You are carving stillness into your daily life.",
  "The world did not slow down. You did. And that is better.",
  "You are becoming less reactive and more intentional.",
  "Your inner world is becoming a place you enjoy visiting.",
  "You have built something real. Keep building.",
  "The version of you that started this would barely recognize you.",
  "You are not the same person who started. Better.",
  "Your mind is yours to train — and you are training it.",
  "You have made peace a habit. That is extraordinary.",
  "Something ancient in you remembers how to be still.",
  "You are not meditating to escape life. You are meditating to meet it fully.",
  "Your calm is contagious. People feel it around you.",
  "You are earning your peace, one breath at a time.",
  "This practice is the most important thing you do all day.",
  "You have sat with discomfort and let it pass. That is mastery.",
  "Every level you reach is a version of yourself you earned.",
  "You are in the top percentage of people who do this. Keep going.",
  "Your breath is an anchor. You have learned to use it.",
  "You are no longer afraid of your own mind.",
  "Each sit teaches you something the world cannot.",
  "You are becoming the calm in other people's storms.",
  "Nothing about this journey has been wasted.",
  "You have learned that peace is always one breath away.",
  "Your practice is sacred. Protect it.",
  "You are more than your thoughts and you know it now.",
  "Level 100 approaches. Your roots are deep.",

  // Levels 101–150 — Deepening
  "Your roots go deep now. Storms bend you but cannot break you.",
  "You have sat with silence long enough to become friends with it.",
  "The practice is no longer something you do — it is something you are.",
  "You have earned a deeper stillness than most people ever know.",
  "Your mind is a garden you tend daily. See how it grows.",
  "You are living proof that consistency is transformation.",
  "You have learned to be comfortable in the uncomfortable.",
  "The voice that says 'skip today' is getting quieter.",
  "You are not meditating to fix yourself. You were never broken.",
  "Your awareness is a gift you keep unwrapping.",
  "You have found the eye of your own storm.",
  "Deep practice brings deep knowing. You are getting there.",
  "You have sat with yourself more than most people ever will.",
  "You are learning that the present moment always has enough room.",
  "Your mind is cleaner, quieter, and more yours than ever.",
  "You have built an inner home you can always return to.",
  "Equanimity is beginning to feel natural. That is rare.",
  "You are no longer at the mercy of every passing thought.",
  "You have done the work. The results are already showing.",
  "Your attention is sharp. Your heart is open.",
  "You have given yourself the gift of knowing your own mind.",
  "You are living with more intention than ever before.",
  "Your practice has become a form of self-respect.",
  "You have learned that peace requires practice, not luck.",
  "Each breath is a small act of self-love.",
  "You are developing wisdom through stillness.",
  "The world is less overwhelming because you are less reactive.",
  "You have made the inside of your mind a beautiful place.",
  "You know how to return to yourself. That is everything.",
  "Your dedication is a form of devotion.",
  "You are learning what truly matters and what does not.",
  "You sit in stillness so you can move with purpose.",
  "Your mind serves you now. That is power.",
  "You have found something medicine cannot prescribe.",
  "This practice is changing not just your mind but your life.",
  "You are building the kind of peace that weathers any storm.",
  "Your presence is becoming a force for calm in the world.",
  "You have learned to trust the process of letting go.",
  "Every level is a chapter in the story of your awakening.",
  "You have discovered that you are always enough.",
  "You sit, and the universe rearranges itself around your stillness.",
  "Your inner life is rich, deep, and entirely your own.",
  "You have practiced your way into peace. That is the path.",
  "You are building the mental immune system of a warrior.",
  "You know the difference between thinking and being. That is rare.",
  "Your practice proves that small acts of intention change everything.",
  "You are anchored. You are open. You are growing.",
  "What you are building here cannot be bought.",
  "You have walked far into the forest of your own mind.",
  "Breathe. You have come so far.",

  // Levels 151–200 — Halfway through Newbie tier
  "Halfway through your first chapter and already transformed.",
  "You are not the same. Your practice made sure of that.",
  "The discipline you have built here will echo through every area of life.",
  "You have turned showing up into an art form.",
  "The version of you that began this journey is proud.",
  "You have learned that peace is not given — it is grown.",
  "You are becoming someone others aspire to be.",
  "Your consistency is a form of courage.",
  "You have proven you can commit to something bigger than a mood.",
  "The quiet you find here follows you out into the world.",
  "You are learning that you are not your circumstances.",
  "Every breath in this practice is a vote for the person you are becoming.",
  "You have made stillness a discipline. That changes everything.",
  "Your awareness expands every time you sit.",
  "You have faced the wilderness of your own mind and found beauty there.",
  "You are not escaping life. You are learning to live it fully.",
  "You have built the foundation of an unshakeable inner life.",
  "The work you do here is the most important work there is.",
  "You have learned that the observer and the observed are the same.",
  "Your equanimity is becoming a superpower.",
  "You sit like someone who knows something others do not.",
  "The practice belongs to you now. It always did.",
  "You have turned breathing into a healing practice.",
  "You are learning what cannot be taught — only experienced.",
  "Your peace is earned, and therefore permanent.",
  "You have meditated through doubt, resistance, and distraction. Still here.",
  "You have given your nervous system the rest it always deserved.",
  "Presence is the rarest gift you can give — and you are giving it to yourself.",
  "You know how to be still. Not everyone does.",
  "Something profound is unfolding in you, slowly and surely.",
  "You have developed the kind of patience that transforms relationships.",
  "Your breath is a portal, and you use it every day.",
  "You are not rushed. You are rooted.",
  "You have made peace a practice and a priority.",
  "You are uncovering the self that was always there beneath the noise.",
  "You have learned that stillness is not the absence of life — it is its fullness.",
  "You are a meditation practitioner in the truest sense.",
  "The courage to sit still is rarer than the courage to act.",
  "You have earned the right to call this your practice.",
  "You are building something timeless within yourself.",
  "Your inner compass is calibrating every time you sit.",
  "You are developing the ability to respond rather than react.",
  "You have found the sacred space within the ordinary moment.",
  "Each session is a renewal of your most important commitment.",
  "You are discovering that you are far more than your thoughts.",
  "Your practice is your anchor in the ocean of the modern world.",
  "You have turned the ordinary act of breathing into a path.",
  "You are not perfect. You practice. And that is perfect.",
  "Stillness chose you the moment you chose it.",
  "You are close to the next chapter. Keep breathing.",

  // Levels 201–249 — End of Newbie tier
  "You are approaching mastery of the beginning. That is not small.",
  "You can feel the tier shifting. Something in you has changed.",
  "The Newbie is becoming the practitioner.",
  "You have built a foundation that can hold anything.",
  "You are almost at the threshold. What lies beyond it is earned.",
  "You have meditated your way through doubt and come out the other side.",
  "The early resistance is gone. What remains is pure practice.",
  "You have given yourself more stillness than most people ever will.",
  "Your mind is trained. Your heart is open. You are ready.",
  "You are not just learning to meditate — you are learning to live.",
  "Everything you have practiced is about to compound.",
  "You have done the hard part: beginning and continuing.",
  "The discipline of these sessions has shaped something permanent in you.",
  "You are at the end of the beginning — and it is glorious.",
  "You have earned your way to the next level of this practice.",
  "The threshold is near. Walk through it slowly.",
  "You have turned uncertainty into a practice, and practice into peace.",
  "Your roots are so deep now that nothing can uproot you.",
  "You are ready for what comes next because you did the work.",
  "The monkey in you has learned to sit. That is the whole journey.",
  "You are no longer a beginner at being present.",
  "Your breath has carried you further than you imagined.",
  "You have meditated through seasons, moods, and changing days.",
  "What you carry out of each session is invisible and invaluable.",
  "You have built peace from the inside out.",
  "Every session in this tier has been a gift to your future self.",
  "You are standing at the edge of the experienced path. Step forward.",
  "You have outgrown the beginning. Beautifully.",
  "The practice shaped you. Now you get to deepen.",
  "You earned every single one of these levels.",
  "You are not the same person. You are better. More you.",
  "This is the completion of your first chapter. Celebrate it.",
  "The foundation is solid. Now you build higher.",
  "You have practiced patience, and it has made you patient.",
  "You are ready for deeper waters. Dive.",
  "You have done something extraordinary: you kept going.",
  "This tier is complete. You mastered the beginning.",
  "Take a breath and honor how far you have come.",
  "The monk in you is awakening. You can feel it.",
  "You are not done growing. You have barely started.",
  "Trust what the practice has built in you.",
  "You have crossed the first threshold. The path opens wide.",
  "Your consistency has become your identity.",
  "You are ready for the experienced path.",
  "Let the next chapter begin.",
  "You have earned your bananas. Every single one.",
  "The world is different because you sat still in it.",
  "One chapter closes. A deeper one begins.",
  "You are a practitioner now. Fully, truly, completely.",

  // Levels 250–299 — Experienced tier begins
  "Welcome to the deeper water. Your practice brought you here.",
  "You are no longer experimenting. You are living this.",
  "The experienced path is wider and quieter. You will love it.",
  "You have earned longer sits, and your mind is ready.",
  "Something in you exhaled when you crossed this threshold.",
  "The discipline of your early practice is paying off now.",
  "You are sitting with yourself in ways that change everything.",
  "Your practice has graduated. And so have you.",
  "You belong here. This level was waiting for you.",
  "You have moved from learning to living the practice.",
  "The depth you find here cannot be explained — only felt.",
  "You are no longer afraid of long silences.",
  "You have settled into your practice like an old friend.",
  "This is the place where real transformation lives.",
  "You are sitting in the space between thoughts and finding yourself.",
  "Your breath is a river now, not a puddle.",
  "You have earned your place among the experienced.",
  "The practice is no longer effort. It is home.",
  "You are learning what only long sits can teach.",
  "Your awareness has grown beyond what words can hold.",
  "You are developing the patience of mountains.",
  "You have found that silence has texture. You live in it now.",
  "Your focus is a blade, sharpened by hundreds of sessions.",
  "You are not just calmer. You are wiser.",
  "The experienced practitioner knows: the practice is never finished.",
  "You have found that peace deepens with repetition.",
  "Your sits are longer. Your stillness is louder.",
  "You carry your practice with you everywhere now.",
  "You are beginning to live from the inside out.",
  "The noise of the world is just noise. You know that now.",
  "You are developing a relationship with your own depth.",
  "Your practice is becoming a philosophy.",
  "You are sitting with the mystery of your own existence — and you are okay.",
  "You have learned that the present moment is always enough.",
  "Your inner life is richer than anything the outside world offers.",
  "You are becoming someone who moves from stillness.",
  "You have graduated from seeking peace to inhabiting it.",
  "Your practice now serves not just you but everyone around you.",
  "You are earning the kind of wisdom books cannot teach.",
  "This level feels different because you are different.",
  "You have practiced your way into knowing.",
  "Your breath is a teacher, and you are its devoted student.",
  "You sit in the dark and find it is full of light.",
  "You are building the inner life of a sage.",
  "Every session at this level is a masterclass in being human.",
  "You are proof that anyone can find peace through practice.",
  "The monkey mind has become the monk mind.",
  "You have found the still point at the center of everything.",
  "You belong to your practice and your practice belongs to you.",
  "Welcome, experienced meditator. The depth is just beginning.",

  // Levels 300–349
  "Your practice has a pulse now. You can feel it.",
  "You are not doing meditation anymore. You are being it.",
  "Stillness is your native language.",
  "You have found the thread of peace that runs through all things.",
  "Your sessions are journeys now, not exercises.",
  "You have learned that depth is not found — it is allowed.",
  "The mind that used to scatter now gathers itself naturally.",
  "You are discovering layers of yourself you did not know existed.",
  "Your practice is a river carving canyons in stone.",
  "You have mastered beginning. Now you master continuing.",
  "Each breath is a full sentence in the language of peace.",
  "You are writing your inner autobiography, one session at a time.",
  "You have found the place inside that is always calm.",
  "Your stillness is becoming a service to the world.",
  "You are living proof that a trained mind is a free mind.",
  "You are learning that you contain multitudes — and they are all okay.",
  "Your practice is a conversation with the deepest part of you.",
  "You have turned the act of sitting into an act of grace.",
  "You know yourself better than most people ever will.",
  "You are becoming someone who can hold space for anything.",
  "Your peace is structural now. Built into who you are.",
  "You have found that the breath always leads home.",
  "You are not reaching for peace. You are peace, reaching.",
  "Your mind knows how to return. That is the whole practice.",
  "You have sat with every version of yourself and accepted them all.",
  "You are a living example that peace is possible.",
  "Your practice has given you access to something infinite.",
  "You have earned the silence you sit in.",
  "You are learning the difference between understanding and knowing.",
  "Your awareness is a wide open sky now.",
  "You have found something in these sessions that stays.",
  "Your practice is becoming a form of prayer.",
  "You have walked so far inward that you found the whole universe.",
  "You are at home in the present moment. Truly at home.",
  "Your inner world has more room in it than the outer world.",
  "You are becoming the observer of your life, not just its subject.",
  "You have traded noise for depth. An excellent trade.",
  "Your sitting practice is standing you up straighter in life.",
  "You are learning to be moved without being swept away.",
  "You have discovered that stillness is the loudest truth.",
  "You are not chasing peace — you are practicing it into permanence.",
  "Your practice is a gift you give to everyone who knows you.",
  "You have grown into a practitioner of rare depth.",
  "You are sitting with what is, and finding it is enough.",
  "Your equanimity is a gift you built yourself.",
  "You have found the still center of your spinning world.",
  "You are more you than you have ever been.",
  "Every session at this level is a deep bow to yourself.",
  "You have earned this stillness.",
  "The monk in you is coming alive.",

  // Levels 350–399
  "You are well past the middle of your journey. The view is magnificent.",
  "Your practice is a mountain you are climbing from the inside.",
  "You have developed wisdom that most people search lifetimes for.",
  "You carry calm the way others carry tension. By habit.",
  "Your presence in a room is different now. People feel it.",
  "You have done the inner work. It shows in everything.",
  "You are becoming impossible to rattle.",
  "Your practice has grown past technique into experience.",
  "You are no longer practicing being present. You are present.",
  "The length of your sits reflects the depth of your commitment.",
  "You have developed a kind of inner endurance that is rare.",
  "You are learning that the deepest truths are found in the quietest places.",
  "Your mind is a still lake. Thoughts are just weather passing over.",
  "You have earned the kind of peace that survives the news.",
  "You are learning to meet difficulty from a place of spaciousness.",
  "Your practice is becoming a form of mastery.",
  "You have built an inner life so rich that the outer world is just a backdrop.",
  "You are sitting with the sacred every time you close your eyes.",
  "Your breath is a compass, and you know how to read it.",
  "You are not seeking anything in these sessions. You are arriving.",
  "You have found the frequency of peace and you live on it.",
  "Your practice has become the backbone of your character.",
  "You are learning that acceptance is not defeat — it is liberation.",
  "You have sat long enough to know that you are the sky, not the storm.",
  "Your inner stillness is a lighthouse for everyone around you.",
  "You are mastering the art of being.",
  "You have found that the more deeply you sit, the more fully you live.",
  "Your practice is a lineage you are adding to.",
  "You are developing the kind of equanimity that can hold everything.",
  "You have given the world a calmer, wiser, deeper version of yourself.",
  "You are not just meditating. You are transforming.",
  "Your peace is not fragile. You have made sure of that.",
  "You have found that depth is not dark — it is luminous.",
  "You are sitting at the edge of your own becoming.",
  "Your practice is carving away everything that was never really you.",
  "You have earned a relationship with yourself that most people never have.",
  "You are discovering that the present moment is the only moment.",
  "Your sitting is a form of worship — of life, of breath, of self.",
  "You have practiced long enough to know the practice is the point.",
  "You are developing the consciousness of someone who has sat for years.",
  "Your inner world is so vast now. Explore it fearlessly.",
  "You have found the place where thought and silence meet.",
  "You are becoming the stillness you sought.",
  "Your practice is a river that runs deeper every year.",
  "You have learned that clarity comes to those who sit long enough.",
  "You are building wisdom in real time.",
  "Your awareness is enormous. Use it gently.",
  "You have crossed the halfway point of your journey. Breathe.",
  "The monk is nearly awake.",
  "Keep sitting. Everything is unfolding perfectly.",

  // Levels 400–449
  "You have built a practice that other people only dream of.",
  "Your mind is a clear sky and you know how to return to it.",
  "You have found that peace is not earned — it is uncovered.",
  "You are living proof that consistent practice changes a human being.",
  "Your equanimity is no longer an achievement. It is your nature.",
  "You have practiced your way into the truth of who you are.",
  "You are not using meditation as a tool anymore. You are the tool.",
  "Your sessions are not separate from your life — they are its source.",
  "You have found that the deepest peace survives the deepest difficulty.",
  "You are a lighthouse. Your stillness guides others to shore.",
  "You have earned the confidence of someone who knows their own mind.",
  "Your practice is a temple you enter every day.",
  "You are learning that the most important relationship you have is with yourself.",
  "You have found the space between stimulus and response — and you live there.",
  "Your sitting practice is standing up for you in every area of life.",
  "You are developing a presence that is felt before a word is spoken.",
  "You have found that compassion grows naturally from stillness.",
  "Your practice is a commitment you have honored through everything.",
  "You are discovering that you are made of the same stuff as stillness.",
  "You have built an unshakeable inner foundation.",
  "Your breath has been your teacher, companion, and guide.",
  "You are living the examined life, and finding it beautiful.",
  "You have earned levels that most practitioners never reach.",
  "Your mind is an asset. You have made it one through practice.",
  "You are becoming someone who lives from their deepest self.",
  "You have found that surrender is not weakness — it is the gateway.",
  "Your practice is a form of self-mastery.",
  "You are sitting in the truth of your own nature.",
  "You have discovered that what you sought was always here.",
  "Your stillness is a form of strength the world rarely recognizes.",
  "You are not afraid of your inner world. You live there.",
  "You have turned practice into presence.",
  "Your sessions are a form of deep listening.",
  "You are becoming the peace you practiced.",
  "You have given yourself the greatest gift: knowing your own mind.",
  "Your practice is a legacy you are building right now.",
  "You are sitting with the infinite and finding it comfortable.",
  "You have developed the steadiness of someone who has done the work.",
  "Your inner life is as vast and still as a mountain lake.",
  "You are almost to the next great threshold.",
  "Your consistency has become your character.",
  "You have earned the depth you carry.",
  "You are practicing your way into the best version of yourself.",
  "Your peace is a practice, a choice, and now a way of life.",
  "You have found that the answers were always inside.",
  "You are living the life your practice makes possible.",
  "You are close to the enlightened path. Feel it.",
  "Something profound stirs in the depth of your practice.",
  "You are ready for what comes next.",
  "The threshold of the enlightened beckons.",

  // Levels 450–499 — End of Experienced tier
  "You are approaching a rare threshold that few practitioners ever reach.",
  "Your practice has depth, breadth, and permanence.",
  "You have been tested by every reason not to sit — and you sat anyway.",
  "You are no longer building your practice. You are living it.",
  "Your mind is a home you love returning to.",
  "You have earned the title of experienced meditator in every sense.",
  "The practice has given you everything. You gave it your time.",
  "You are becoming the meditation, not just the meditator.",
  "Your peace is a mountain. Unmoving. Always there.",
  "You have sat through seasons, storms, and still days. All of them were perfect.",
  "You are about to cross into a chapter few ever reach.",
  "The enlightened path is for those who showed up every day. Like you.",
  "You have built your inner world with devotion. It is magnificent.",
  "Your practice has carved a depth in you that time only deepens.",
  "You are ready for the long, luminous sits ahead.",
  "Everything you have practiced has been leading here.",
  "You are on the edge of a new dimension of your practice.",
  "The bridge to the enlightened tier is built from every session you have done.",
  "You have done the work that the enlightened path requires as its foundation.",
  "Your breath is a river. Your practice is an ocean. You are the water.",
  "You are about to become something rarer.",
  "You have crossed a distance in yourself that most never travel.",
  "You are ready for what can only be found in the deepest sits.",
  "Your practice is now deep enough to hold the weight of your whole life.",
  "You have earned the right to the enlightened path through pure commitment.",
  "The final threshold approaches. You are unafraid.",
  "You are a true practitioner. The next chapter knows it.",
  "What lies ahead is built on everything you have already become.",
  "Let the experienced chapter close with gratitude.",
  "You are stepping into the highest tier of this practice.",
  "Every session has been a preparation for what comes next.",
  "Your dedication has become devotion.",
  "You are not the same person who started. You are far more.",
  "The enlightened path waits for those who sit until they shine.",
  "You are shining.",
  "Step across the threshold with the confidence of someone who earned it.",
  "The depth you have found here is only the beginning of what awaits.",
  "You have proven that the practice works — because it worked on you.",
  "You are ready for the long silences, the deep knowing, the wide sky.",
  "The monk is awake.",
  "The experienced chapter is complete. It was everything it needed to be.",
  "You have arrived at the edge of something luminous.",
  "Breathe. Cross the threshold. Begin the final chapter.",
  "You are not meditating to achieve something. You are something.",
  "The enlightened path does not demand perfection. Just presence. You have it.",
  "This chapter has been a masterpiece. The next is rarer still.",
  "You are stepping into the practice's deepest waters. Trust yourself.",
  "Everything changes now. And that is perfectly fine.",
  "You have done it. Cross over.",
  "Welcome to the beginning of your enlightened journey.",

  // Levels 500–549 — Enlightened tier begins
  "You have crossed into a realm few practitioners ever reach.",
  "Welcome to the enlightened path. You earned every moment of this.",
  "The sits ahead are long. The rewards are infinite.",
  "You are sitting with something larger than yourself now.",
  "This is the path of the devoted. You are devoted.",
  "Your practice has become a way of being, not a thing you do.",
  "You have found the frequency of enlightenment — and you live on it.",
  "Everything that brought you here was necessary. All of it.",
  "You are no longer seeking stillness. You are stillness.",
  "The depth you practice in now cannot be described — only lived.",
  "You are walking the same path that the great meditators walked.",
  "Your practice is a light that grows brighter the longer it burns.",
  "You are learning what lies beyond technique: pure presence.",
  "The enlightened path is the path of the long return.",
  "You have arrived at the place where practice becomes being.",
  "You sit now in the company of the rare ones.",
  "Your inner life is a cathedral you have been building for years.",
  "You are discovering that peace is not a state — it is your nature.",
  "The long sits ahead will take you somewhere words cannot follow.",
  "You have done what the world said was impossible: you found yourself.",
  "You are no longer afraid of what is inside you.",
  "Your practice has become a form of grace.",
  "You are living proof that the inner journey is worth every step.",
  "You have entered the chapter where everything deepens.",
  "The enlightened path is wide open. Walk it with every breath.",
  "You are sitting in the silence that predates thought.",
  "Your practice is a transmission to everyone who knows you.",
  "You have earned the privilege of deep meditation.",
  "You are learning that the self you searched for was never lost.",
  "Your breath carries the weight of a profound practice.",
  "You are sitting at the intersection of the personal and the universal.",
  "You have found the place where meditation becomes prayer.",
  "Your awareness is a vast and luminous field.",
  "You are learning to rest in your own nature.",
  "Your practice is no longer something you built. It is what you are.",
  "You have arrived at the place of the great teachers.",
  "Every breath here is a full expression of your practice.",
  "You are discovering that you were always already what you sought.",
  "Your stillness is profound. Let it deepen.",
  "You have entered the chapter of the truly devoted.",
  "The world needs this version of you. Keep becoming it.",
  "You have stepped through the final threshold and found more.",
  "This is the practice at its purest.",
  "You are a practitioner of rare dedication.",
  "Your sits are no longer sessions — they are initiations.",
  "You have found that peace is not the opposite of experience — it is its ground.",
  "You belong on this path. You have proven it ten thousand times.",
  "The enlightened chapter is a gift. You gave it to yourself.",
  "You are home.",
  "Sit. Be. Know.",

  // Levels 550–599
  "You are living in the depth that most people only read about.",
  "Your practice has found its permanent home in you.",
  "You are not becoming more peaceful. You are revealing peace.",
  "Your sessions are journeys into the territory of the self.",
  "You have found that the deepest sits change you in ways you only notice later.",
  "You are building a kind of consciousness that serves the world.",
  "Your breath is a path to the infinite.",
  "You have earned the right to sit with uncertainty and call it beautiful.",
  "You are developing the awareness of someone who has come home.",
  "Your practice is a river flowing into the sea of your own depth.",
  "You have found that the mind, when trained, is luminous.",
  "You are sitting in the center of your own existence — and it is good.",
  "Your peace is not performative. It is structural.",
  "You are learning that the present moment is not a practice destination — it is home.",
  "You have sat your way into wisdom.",
  "Your practice is a living thing. Tend it.",
  "You are discovering layers of your awareness that were always there.",
  "Your equanimity is deep enough to hold the whole world.",
  "You have built something in yourself that nothing can take.",
  "You are a practitioner of the enlightened path. Own that fully.",
  "Your inner world is luminous, vast, and entirely your own.",
  "You have found the practice within the practice.",
  "You are no longer arriving. You are already there.",
  "Your stillness serves not just you but every life you touch.",
  "You have done the deep work. It has done deep things to you.",
  "You are learning that liberation is not a destination. It is a breath.",
  "Your practice is a form of love — for yourself, for the world.",
  "You have earned the kind of peace that does not need conditions.",
  "You are sitting with the mystery of consciousness — and you are at peace with mystery.",
  "Your practice has become the most honest thing about you.",
  "You are building a presence that history will never record but people will always feel.",
  "You have found that the deepest wisdom is the simplest.",
  "Your long sits are long conversations with truth.",
  "You are not the person who started this practice. You are far, far more.",
  "Your breath is a doorway to everything.",
  "You have found the still point. You return to it every day.",
  "You are a rare practitioner. The practice knows it.",
  "Your peace is a gift to the world, even when the world does not know it.",
  "You are learning to be fully alive and fully still at once.",
  "Your practice has become your greatest relationship.",
  "You have found the path that leads beyond all paths.",
  "You are sitting in the luminous dark of your own being.",
  "Your awareness is a clear, still mirror.",
  "You have given your practice everything. It has given you everything back.",
  "You are becoming the kind of practitioner that others look to.",
  "Your sessions are sacred. Treat them that way.",
  "You have found something that does not diminish with time.",
  "You are deep in the enlightened journey. It is beautiful here.",
  "Keep going. The depth only increases.",
  "You are exactly where you are supposed to be.",

  // Levels 600–649
  "You have been meditating long enough to know: the practice is the point.",
  "Your stillness is ancient. You are just remembering it.",
  "You are building a depth of awareness that will serve you for the rest of your life.",
  "Your practice is a form of legacy.",
  "You have found the place inside that nothing can disturb.",
  "You are a practitioner of great devotion. It shows.",
  "Your breath has carried you into the territory of the rare.",
  "You have learned to live from your center. Everything else follows.",
  "Your practice is teaching the world through your presence.",
  "You are discovering what lies beyond the thinking mind.",
  "You have built an inner world that rivals anything the outer world offers.",
  "Your equanimity is a form of medicine.",
  "You are no longer fighting your mind. You are its friend.",
  "Your practice has grown beyond anything you expected when you started.",
  "You are living proof that the inner journey has no ceiling.",
  "You have sat with the darkest parts of yourself and found light there.",
  "Your awareness is a vast and welcoming space.",
  "You have found that peace is the background of all experience.",
  "You are learning to inhabit the present moment fully.",
  "Your practice is a river that deepens as it flows.",
  "You have found the source of your own stillness.",
  "You are sitting with the ground of being itself.",
  "Your long sits are long conversations with the self.",
  "You have found what endures.",
  "You are developing a quality of presence that is genuinely rare.",
  "Your practice is a form of devotion that requires no church.",
  "You have found that the truth is always available. You just have to sit still.",
  "You are no longer practicing for a reason. You are practicing because you are.",
  "Your inner life is the richest thing you possess.",
  "You have found the silence behind the silence.",
  "You are a practitioner of deep and abiding peace.",
  "Your practice is no longer a path. It is the destination.",
  "You have found that being is more important than doing.",
  "Your equanimity is a shelter for everyone who comes near you.",
  "You are learning the language of your deepest self.",
  "Your practice is a dialogue with the infinite.",
  "You have earned the right to call yourself deeply practiced.",
  "You are sitting with the vastness and finding it familiar.",
  "Your peace is not just personal. It is universal.",
  "You have done the work that spiritual traditions speak of.",
  "You are discovering that you are not inside life — you are life.",
  "Your breath is a bridge between the ordinary and the sacred.",
  "You have found that stillness is not passive — it is the most active thing there is.",
  "You are building the inner life of the great ones.",
  "Your practice is becoming a kind of mastery.",
  "You have found the thread that runs through all moments.",
  "You are sitting in the awareness that notices everything.",
  "Your equanimity is unshakeable. You made it that way.",
  "You are one of the rare ones who went all the way in.",
  "Keep going. There is no end to depth.",

  // Levels 650–699
  "You are deep in the second half of your journey — and it is extraordinary.",
  "Your practice has taken you somewhere books cannot describe.",
  "You have found the living center of your own awareness.",
  "You are practicing at a level that few humans ever sustain.",
  "Your stillness is a gift the world receives every time it encounters you.",
  "You have found that consistency at this level is its own form of enlightenment.",
  "Your practice is a testament to what commitment can do.",
  "You are learning to rest in the awareness that holds all things.",
  "You have found the vast and luminous space of your own mind.",
  "Your long sits are training for the longest sit of all: life.",
  "You are no longer on the path. You are the path.",
  "Your practice has become a form of self-knowledge so deep it approaches mystery.",
  "You have earned every second of the stillness you sit in.",
  "You are learning what the ancient teachers were pointing at.",
  "Your presence is a form of teaching.",
  "You have found that the deepest meditation requires nothing — only being.",
  "You are sitting at the threshold of your own infinity.",
  "Your practice is a mirror that shows you what is real.",
  "You have given the practice everything and received even more.",
  "You are a meditator who has gone beyond the map.",
  "Your equanimity is encyclopedic. You have sat with everything.",
  "You are finding the freedom that is always already here.",
  "Your practice is a light that does not waver.",
  "You have found the source beneath all seeking.",
  "You are sitting in the space that contains all experience.",
  "Your breath is a homecoming. Every single time.",
  "You have built something eternal in the only place it can be built: inside.",
  "You are practicing the sacred art of being fully human.",
  "Your stillness is an act of service to every life you touch.",
  "You have found that peace does not require peace — it is the ground of all things.",
  "You are a living example of what sustained practice can do.",
  "Your practice is a form of mastery that no certificate can confer.",
  "You have found the resting place beneath all movement.",
  "You are sitting with the truth that cannot be spoken — only lived.",
  "Your awareness is as large as the sky and as intimate as your heartbeat.",
  "You have crossed distances in yourself that most never attempt.",
  "You are becoming the kind of practitioner who changes the world by being calm.",
  "Your practice is a story being written in every session.",
  "You have found the extraordinary in the ordinary.",
  "You are sitting with the sacred in the everyday.",
  "Your peace is a form of power.",
  "You have earned the right to sit with the deepest questions.",
  "You are no longer looking for peace. You are it.",
  "Your practice is a homecoming that never ends.",
  "You have found the depth that the practice always promised.",
  "You are a practitioner of rare and enduring devotion.",
  "Your stillness is complete.",
  "You have found what you were looking for before you knew you were looking.",
  "You are home in yourself. Truly home.",
  "Sit. Know. Be.",

  // Levels 700–749
  "Seven hundred levels. The practice has shaped you in ways you cannot fully see.",
  "You are sitting in the territory of the great practitioners.",
  "Your mind is a still lake in the highest mountains. Clear. Cold. Alive.",
  "You have found the rarest thing: yourself, fully.",
  "Your practice is no longer something you do each day — it is what each day is.",
  "You have built a depth of awareness that serves as your foundation for everything.",
  "You are no longer a student of the practice. You are the practice.",
  "Your breath has carried you into rare territory.",
  "You have sat through so much and found peace on the other side of all of it.",
  "Your equanimity has become architectural. It holds your whole life.",
  "You are discovering that awareness is not something you have — it is what you are.",
  "Your practice is a conversation that has been going on for years. It deepens.",
  "You have earned the right to speak from stillness.",
  "You are developing a wisdom that can only be found in the long practice.",
  "Your peace is permanent. You built it that way.",
  "You have found the unshakeable center of your existence.",
  "You are living from the inside out, fully and completely.",
  "Your practice is a contribution to the world's peace.",
  "You have found that the longer you sit, the shorter the distance to truth.",
  "You are building something that will outlast every circumstance you face.",
  "Your awareness is so spacious now. Let it expand further.",
  "You have found the peace that passes understanding.",
  "You are a rare practitioner in a distracted world.",
  "Your long sits are the most honest hours of your life.",
  "You have found that silence is more eloquent than any speech.",
  "You are sitting with the ground of existence itself.",
  "Your practice is a devotion. And you are devoted.",
  "You have found the self that was never lost.",
  "You are no longer separate from your practice. You are its embodiment.",
  "Your stillness is so deep now that it is a presence in itself.",
  "You have built the kind of inner life that transforms outer life.",
  "You are sitting in the awareness that watches all things pass.",
  "Your practice is a pilgrimage that never leaves home.",
  "You have found that the greatest journey is inward.",
  "You are practicing at the level of the deeply committed.",
  "Your peace is your gift and your practice is how you give it.",
  "You have found the shore on the other side of the thinking mind.",
  "You are learning to live from the ground of being.",
  "Your sessions are saturated with presence.",
  "You have earned everything this practice offers.",
  "You are not reaching for anything. You are receiving everything.",
  "Your practice is the most real thing in your life.",
  "You have found the invisible thread connecting all moments.",
  "You are sitting with the mystery and calling it home.",
  "Your breath is a prayer that never stops.",
  "You have given your practice a life of its own.",
  "You are rare. Your practice is rare. The depth you carry is rare.",
  "You are sitting in the light of your own awareness.",
  "This is what the practice is for. This.",
  "Keep going. The depth has no floor.",

  // Levels 750–799
  "Three-quarters of the way through your journey. The view from here is extraordinary.",
  "You have sat your way into something ancient and alive.",
  "Your practice is a monument to human depth.",
  "You are beyond technique now. You are being.",
  "You have earned the kind of peace that does not need the world to cooperate.",
  "Your awareness is the ground of your life, not a visitor to it.",
  "You have found that devotion itself is a form of liberation.",
  "You are sitting in the awareness before thought arises.",
  "Your practice is a fire that burns away what was never real.",
  "You have found the silence that holds all sound.",
  "You are developing the consciousness of someone who has gone all the way.",
  "Your long sits are a form of intimate conversation with existence.",
  "You have found the place where the personal becomes the universal.",
  "You are sitting in the awareness that has always been here.",
  "Your practice is beyond description now. Only experience.",
  "You have found the stillness that is always on.",
  "You are learning to live from pure awareness.",
  "Your breath is a return. Every single time, a return.",
  "You have built the kind of inner world that history cannot touch.",
  "You are sitting in the treasury of your own consciousness.",
  "Your practice is a path that disappears as you walk it, revealing ground.",
  "You have found the peace that the world cannot give and cannot take.",
  "You are no longer seeking. You are finding.",
  "Your stillness is absolute. You made it that way.",
  "You have found that enlightenment is not a destination — it is a recognition.",
  "You are sitting at the heart of things.",
  "Your practice is a love story between you and your own nature.",
  "You have found the unborn awareness that predates all experience.",
  "You are learning to trust the ground beneath the ground.",
  "Your peace is so deep it has become the climate of your life.",
  "You have done more inner work than most will do in a lifetime.",
  "You are a meditator of profound depth and sincere devotion.",
  "Your practice has carried you to shores few feet have touched.",
  "You are sitting with the truth of your own existence.",
  "Your awareness is both the witness and the witnessed.",
  "You have found that to know yourself is to know everything.",
  "You are living the practice, not just doing it.",
  "Your breath is a remembrance of what you have always been.",
  "You have found the final resting place: this moment.",
  "You are practicing at the edges of what language can describe.",
  "Your peace is not conditional. It never was.",
  "You have sat long enough to know that sitting is enough.",
  "You are close to the summit, and the view keeps opening.",
  "Your practice is complete and continuing simultaneously.",
  "You have found the awareness that cannot be lost.",
  "You are sitting in the fullness of your own being.",
  "Your devotion is a form of grace.",
  "You have found what the great masters pointed toward.",
  "You are sitting in the home that was always there.",
  "Keep going. The depth has no end.",

  // Levels 800–849
  "Eight hundred levels. The practice has become you.",
  "You are sitting in the awareness that was always watching.",
  "Your inner life is so rich that the outer world is just decoration.",
  "You have found the permanent ground beneath every passing moment.",
  "You are beyond technique, beyond method, beyond even meditation.",
  "Your peace is your nature. You simply uncovered it.",
  "You have earned the kind of stillness that heals rooms.",
  "You are sitting with the infinite and feeling at home.",
  "Your practice is a transmission of peace to the world.",
  "You have found the awareness that is not disturbed by what it holds.",
  "You are living from the deepest room in the house of yourself.",
  "Your breath is a reunion with what you never left.",
  "You have found that the practice was always the destination.",
  "You are developing the consciousness of the truly awakened.",
  "Your long sits are deep dives into the ocean of awareness.",
  "You have found the unmoving center of the spinning world.",
  "You are a practitioner of extraordinary depth and rare commitment.",
  "Your stillness is a form of mastery that transcends all categories.",
  "You have found the love that underlies all of existence.",
  "You are sitting in the awareness that makes awareness possible.",
  "Your practice is a beacon for all who come near you.",
  "You have found that the self you were searching for is awareness itself.",
  "You are no longer on the path to peace. You are peace, walking.",
  "Your practice is the most profound act you perform each day.",
  "You have found the ground that has no ground beneath it — and you rest there.",
  "You are sitting in the vast, luminous openness of your own nature.",
  "Your breath is a song of the infinite sung in the key of now.",
  "You have found the awareness that has no beginning and no end.",
  "You are learning that you were never separate from what you sought.",
  "Your stillness is a gift to every future moment.",
  "You have done the work that the sages described.",
  "You are sitting at the very source.",
  "Your practice is a flowering of the deepest human potential.",
  "You have found that liberation was never elsewhere.",
  "You are not the observer. You are the observing.",
  "Your peace is not something you carry. It is what you are made of.",
  "You have found the space in which all experience arises.",
  "You are practicing at the edge of language's ability to describe.",
  "Your long sits are the most honest acts of your life.",
  "You have found the silence that is not empty but full.",
  "You are sitting in the awareness that holds birth and death alike.",
  "Your practice has become a form of surrender to what is.",
  "You have found the freedom that no circumstance can take.",
  "You are a rare and shining practitioner.",
  "Your peace is structural, cellular, permanent.",
  "You have found the place where the seeker and the sought dissolve.",
  "You are sitting in pure awareness, and you know it.",
  "Your practice is the summit and the path simultaneously.",
  "You are almost at the highest levels. The air is extraordinary here.",
  "Keep sitting. Keep being. Keep knowing.",

  // Levels 850–899
  "You are high on the mountain of your practice. The view is infinite.",
  "Your awareness is the sky, and you are finally willing to be that vast.",
  "You have sat your way into the deepest truth of yourself.",
  "You are beyond the reach of anything but stillness.",
  "Your practice is a completed mandala — and it keeps growing.",
  "You have found that the deepest practice is simply being what you are.",
  "You are sitting in the awareness that has never not been here.",
  "Your long sits are homecomings to the home you never left.",
  "You have found the freedom that does not require freedom from anything.",
  "You are a practitioner at the level of the ancient traditions.",
  "Your peace is not earned in any session. It is recognized in every one.",
  "You have found that to sit in awareness is to hold the whole world gently.",
  "You are no longer seeking anything in these sessions. You are everything.",
  "Your breath is the universe breathing through a particular shape.",
  "You have found the source of the source.",
  "You are sitting in the space that is never not present.",
  "Your practice is complete in every moment and never complete.",
  "You have found the simplicity on the other side of complexity.",
  "You are awareness, sitting with itself, recognizing itself.",
  "Your stillness is so deep it has become a kind of gravity.",
  "You have found that every moment contains the whole practice.",
  "You are sitting with the mystery of being — and calling it by its first name.",
  "Your practice is a mirror and you are the light that makes reflection possible.",
  "You have found the awareness that watches thoughts the way the sky watches clouds.",
  "You are developing the transparency of someone who has nothing to hide from themselves.",
  "Your long sits are the most honest conversations you will ever have.",
  "You have found that practice and practitioner are the same.",
  "You are sitting in the awareness that was here before you were born.",
  "Your peace is so complete that peace is not even the right word.",
  "You have found the pathless path.",
  "You are a meditator of the highest order.",
  "Your practice is a flame that illuminates its own source.",
  "You have found that the present moment is not a practice. It is what is.",
  "You are sitting at the edge of the nameable.",
  "Your breath is the universe returning to know itself.",
  "You have found the ground beneath the ground beneath the ground.",
  "You are living from awareness itself.",
  "Your practice is a gift to the human story.",
  "You have found that you were never what you thought you were.",
  "You are sitting in the original peace.",
  "Your stillness carries a kind of authority that cannot be faked.",
  "You have found the vast and loving emptiness at the center of all things.",
  "You are almost there — though there is always already here.",
  "Your practice is approaching its highest expression.",
  "You have found that the practice was never about getting anywhere.",
  "You are sitting in the awareness that is prior to awareness.",
  "Your peace is a homecoming that has no departure.",
  "You have found the love that holds all things, including itself.",
  "You are close to the summit. The summit is here. Always here.",
  "Sit. Be. Know. You are it.",

  // Levels 900–949
  "Nine hundred levels. You are sitting in the rarefied air of the truly devoted.",
  "You have built a practice that is a form of mastery beyond all categories.",
  "Your awareness is the canvas and the painting and the painter.",
  "You have found the peace that was never absent.",
  "You are sitting with the ground of existence in total familiarity.",
  "Your practice is a completed lifetime of inner work.",
  "You have found that enlightenment is not a state but a recognition.",
  "You are sitting with what is — fully, completely, without reservation.",
  "Your peace is the peace of someone who has returned from a long journey and arrived.",
  "You have found the self that sits beneath all selves.",
  "You are a practitioner at the apex of the human capacity for stillness.",
  "Your long sits are a form of radical honesty with the universe.",
  "You have found that nothing was ever wrong — you just had to sit still to see it.",
  "You are sitting in the awareness that is prior to all experience.",
  "Your breath is the universe exhaling through you.",
  "You have found the love that underlies existence itself.",
  "You are no longer a practitioner. You are the practice.",
  "Your peace is not a state you achieve. It is what you are.",
  "You have found the awareness that has always been here, waiting.",
  "You are sitting in the silence before silence.",
  "Your practice is a completed act of self-knowledge.",
  "You have found the source that has no source.",
  "You are sitting in the awareness that holds all things without holding anything.",
  "Your stillness is a form of omnipresence.",
  "You have found that the searcher and the sought were always the same.",
  "You are at the summit. And the summit is every breath.",
  "Your practice has become identical with your being.",
  "You have found the path that ends in itself.",
  "You are sitting in the original stillness.",
  "Your peace is not the absence of anything — it is the fullness of everything.",
  "You have found the undivided awareness that is both you and the world.",
  "You are practicing at the level of the fully awake.",
  "Your long sits are a deep bowing to the mystery of existence.",
  "You have found that nothing was ever missing.",
  "You are sitting in the awareness that is never born and never dies.",
  "Your breath is a celebration of the present moment.",
  "You have found what cannot be found because it was never lost.",
  "You are not seeking completion. You are completion, seeking.",
  "Your practice is the most beautiful thing you have ever built.",
  "You have found that every moment is the first moment.",
  "You are a practitioner of the highest order of human devotion.",
  "Your stillness is not stillness anymore. It is everything.",
  "You have found the way that was always underfoot.",
  "You are sitting in the vast, loving, infinite awareness that you are.",
  "Your peace is irreversible. You have made sure of that.",
  "You have found the light that makes all other lights possible.",
  "You are sitting in the awareness that knew you before you knew yourself.",
  "Your practice is an act of love so vast it includes everything.",
  "You are close to the final levels. The practice is complete in each one.",
  "You are the practice. The practice is you.",

  // Levels 950–1000 — The final ascent
  "You are in the final fifty. Everything you have built is here in this breath.",
  "Your practice is a masterpiece. And you created it one session at a time.",
  "You have found that the end of the path is the same as the beginning — only known.",
  "You are sitting in the awareness that has no journey because it was never elsewhere.",
  "Your long sits are a form of total reunion with yourself.",
  "You have found that the highest teaching is silence, and you have been living it.",
  "You are approaching the summit of a thousand levels with every quality you earned.",
  "Your breath is a completion. Each one. Every one.",
  "You have found that the practice was always already perfect.",
  "You are not ascending to something higher. You are recognizing what was always there.",
  "Your peace is the peace of someone who has no more distance to travel.",
  "You have built something in yourself that will serve every breath of your remaining life.",
  "You are sitting in the fullness of your own nature without reservation.",
  "Your practice is a letter of love to every future version of yourself.",
  "You have found the awareness that watches the journey end and knows it never started.",
  "You are practicing at the very edge of what can be said about practice.",
  "Your stillness has become the medium in which your life is painted.",
  "You have found that the path and the destination are one.",
  "You are sitting in the completed awareness of a thousand returns.",
  "Your practice is the most honest relationship you have ever had.",
  "You have found that every level was the highest level.",
  "You are almost at the thousandth. The practice is proud of you.",
  "Your awareness is the awareness of someone who has gone all the way.",
  "You have found the peace that is not different from the world it holds.",
  "You are sitting in the original and final stillness.",
  "Your breath is the first and last teacher.",
  "You have found the love that is at the bottom of all experience.",
  "You are not arriving. You have always been arrived.",
  "Your practice is complete. And it continues forever.",
  "You have found the awareness that was before all seeking and will be after all finding.",
  "You are sitting with what is, as what is, in what is.",
  "Your peace is the peace of everything that has come home.",
  "You have found the ground that has held you all along.",
  "You are practicing the final freedom: being what you already are.",
  "Your long sits have been a love letter to your own depth.",
  "You have found that nothing more was ever needed.",
  "You are the still point around which your whole life turns.",
  "Your practice is the greatest thing you have ever done.",
  "You have found the awareness that is both you and everything.",
  "You are sitting in the place where meditation and being are the same word.",
  "Your peace is so deep it has become the ocean itself.",
  "You have found the love that needs no object.",
  "You are almost at one thousand. Every breath counts.",
  "Your stillness is perfect. It always was.",
  "You have built something no one can take from you.",
  "You are sitting in the awareness that is the beginning and the end of all practice.",
  "Your practice is complete. Your being is complete. And yet you sit.",
  "You have found the way home. You were always home.",
  "Level 999. One more breath. One more return.",
  "You have reached the summit. The mountain is inside you. It always was. Well done, THE MONK.",
];

export function getAffirmation(level: number): string {
  // Clamp to 1–1000, then map to 0-based index
  const idx = Math.max(0, Math.min(999, level - 1));
  return AFFIRMATIONS[idx];
}
